<a href="https://colab.research.google.com/github/jaygoode/pytorch_course/blob/main/intro_to_colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [83]:
import torch

In [111]:
tensor_2d = torch.randn(3,5)
tensor_2d

tensor([[ 0.7906, -0.6410,  0.1660,  0.1553, -1.4610],
        [ 0.6242,  0.4993,  0.0823,  1.3443, -0.6000],
        [-1.4257,  0.2889, -1.0798, -0.0413, -0.8904]])

In [112]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [113]:
#reshape and view
my_torch = my_torch.reshape(2,5)
my_torch


tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [87]:
#reshape if we dont know the num of items using -1
my_torch2 = torch.arange(10)
my_torch2



tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [88]:
my_torch2 = my_torch2.reshape(2,-1)
my_torch2

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [89]:
import torch.nn as nn
import torch.nn.functional as F

In [114]:
class Model(nn.Module):
  def __init__(self, in_features=4, h1=8, h2=9, out_features=3):
    super().__init__()
    self.fc1=nn.Linear(in_features, h1)
    self.fc2=nn.Linear(h1,h2)
    self.out=nn.Linear(h2, out_features)

  def forward(self, x):
    x = F.relu(self.fc1(x))
    x = F.relu(self.fc2(x))
    x = self.out(x)
    return x



In [115]:
torch.manual_seed(41)
model = Model()

In [92]:
import matplotlib.pyplot as plt
import pandas as pd
%matplotlib inline

In [93]:
url = "https://gist.githubusercontent.com/curran/a08a1080b88344b0c8a7/raw/0e7a9b0a5d22642a06d3d5b9bcbad9890c8ee534/iris.csv"
my_df = pd.read_csv(url)

In [94]:
my_df.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [95]:
my_df["species"] = my_df["species"].replace("setosa", 0)
my_df["species"] = my_df["species"].replace("versicolor", 1)
my_df["species"] = my_df["species"].replace("virginica", 2)
my_df

sepal_length  sepal_width  petal_length  petal_width  species
0             5.1          3.5           1.4          0.2        0
1             4.9          3.0           1.4          0.2        0
2             4.7          3.2           1.3          0.2        0
3             4.6          3.1           1.5          0.2        0
4             5.0          3.6           1.4          0.2        0
..            ...          ...           ...          ...      ...
145           6.7          3.0           5.2          2.3        2
146           6.3          2.5           5.0          1.9        2
147           6.5          3.0           5.2          2.0        2
148           6.2          3.4           5.4          2.3        2
149           5.9          3.0           5.1          1.8        2

[150 rows x 5 columns]

In [97]:

x = my_df.drop('species', axis=1)
my_df["species"] = pd.to_numeric(my_df["species"], errors='coerce').astype(float)
y = my_df["species"]
y

0      0.0
1      0.0
2      0.0
3      0.0
4      0.0
      ... 
145    2.0
146    2.0
147    2.0
148    2.0
149    2.0
Name: species, Length: 150, dtype: float64

In [98]:
import numpy



In [99]:
from sklearn.model_selection import train_test_split

In [ ]:
#train test split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state=41)

y


In [101]:
x_train = torch.FloatTensor(x_train.values)
x_test = torch.FloatTensor(x_test.values)

In [102]:
y_train = torch.FloatTensor(y_train.values)
y_test = torch.FloatTensor(y_test.values)

In [119]:
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(), lr = 0.01)
model.parameters

<bound method Module.parameters of Model(
  (fc1): Linear(in_features=4, out_features=8, bias=True)
  (fc2): Linear(in_features=8, out_features=9, bias=True)
  (out): Linear(in_features=9, out_features=3, bias=True)
)>